<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" tests="12" skipped="0" failures="0" errors="0" timestamp="2020-11-25T14:38:34" hostname="lichangbaodeMacBook-Pro.local" time="2.245">
  <properties/>
  <testcase name="testSetReadOnlyAttribute" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.116"/>
  <testcase name="testInvokeUnexposedMethodWithException" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.11"/>
  <testcase name="testSetAttributeValue" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.112"/>
  <testcase name="testTestLazyConnectionToRemote" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="1.02"/>
  <testcase name="testDifferentProxiesSameClass" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.109"/>
  <testcase name="testSetAttributeValueWithIOException" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.114"/>
  <testcase name="testGetAttributeValue" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.112"/>
  <testcase name="testInvokeNoArgs" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.111"/>
  <testcase name="testProxyClassIsDifferent" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.11"/>
  <testcase name="testInvokeArgs" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.108"/>
  <testcase name="testSetAttributeValueWithCheckedException" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.11"/>
  <testcase name="testSetAttributeValueWithRuntimeException" classname="org.springframework.jmx.access.RemoteMBeanClientInterceptorTests" time="0.112"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[Nov 25, 2020 10:38:34 PM ClientCommunicatorAdmin restart
WARNUNG: Failed to restart: java.net.ConnectException: Connection refused (Connection refused)
Nov 25, 2020 10:38:35 PM ClientIntermediary close
INFORMATION: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

Nov 25, 2020 10:38:35 PM ClientIntermediary close
INFORMATION: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

Nov 25, 2020 10:38:35 PM ClientCommunicatorAdmin restart
WARNUNG: Failed to restart: java.net.ConnectException: Connection refused (Connection refused)
Nov 25, 2020 10:38:36 PM ClientCommunicatorAdmin restart
WARNUNG: Failed to restart: java.net.ConnectException: Connection refused (Connection refused)
]]></system-err>
</testsuite>
